api_platform:
    mapping:
        paths: [
            '%kernel.project_dir%/src/CoralMedia/Component/Api/Security/Model'
        ]
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            items_per_page: 15
