vich_uploader:
    db_driver: orm

    mappings:
        users:
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha256', length: 40 }
            uri_prefix: uploads/images/users
            upload_destination: '%kernel.project_dir%/public/uploads/images/users'
        media_object:
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha256', length: 5 }
            uri_prefix: uploads/media
            upload_destination: '%kernel.project_dir%/public/uploads/media'