# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters: ~

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    CoralMedia\Bundle\FrameworkBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../CoralMediaFrameworkBundle.php'
            - '../../Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    CoralMedia\Bundle\FrameworkBundle\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    CoralMedia\Component\WebProfiler\DataCollector\ContainerDataCollector:
        public: false
        tags:
            -
                name: 'data_collector'
                id: 'container'
                template: '@CoralMediaFramework/Collector/container.html.twig'

    CoralMedia\Component\Doctrine\Event\TimeStampableEntitySubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }

    CoralMedia\Component\Api\Swagger\Decorator\AuthenticationTokenDecorator:
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@CoralMedia\Component\Api\Swagger\Decorator\AuthenticationTokenDecorator.inner' ]
        autoconfigure: false

    CoralMedia\Component\Api\Swagger\Decorator\AuthenticationTokenDecorator26:
        decorates: 'api_platform.openapi.factory'
        autoconfigure: false