# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters: ~

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    CoralMedia\Bundle\SecurityBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../CoralMediaSecurityBundle.php'
            - '../../Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    CoralMedia\Bundle\SecurityBundle\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    CoralMedia\Component\Api\Security\DataPersister\UserDataPersister:
        bind:
            $decoratedDataPersister: '@api_platform.doctrine.orm.data_persister'
    CoralMedia\Component\Api\Security\DataPersister\GroupDataPersister:
        bind:
            $decoratedDataPersister: '@api_platform.doctrine.orm.data_persister'

    CoralMedia\Component\Api\Security\Voter\ApiResourceVoter:
        tags: ['security.voter']

    CoralMedia\Component\Api\Security\Token\Logout\Event\LogoutEventSubscriber:
        tags:
            -   name: kernel.event_subscriber

    CoralMedia\Component\Api\Security\Event\CurrentUserSubscriber:
        tags:
            -   name: kernel.event_subscriber

    # Default token manager overridden
    # Check https://github.com/markitosgv/JWTRefreshTokenBundle/issues/200 for further details.
    gesdinet.jwtrefreshtoken.refresh_token_manager:
        class: CoralMedia\Component\Api\Security\Token\Doctrine\RefreshTokenManager
        public: true
        arguments: [
            '@doctrine.orm.default_entity_manager',
            'Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken'
        ]